name = "BasicCraft"
author = "MisileLaboratory"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f69632fb9ddea1e69c25062016c423d7caef92c85c779835a6cad2474bd8da5f"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
