name = "BasicCraft"
author = "MisileLaboratory"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d842048baddd0f79685b34a2efe43cdeccd7829ccda2573fe25e3d18d97d6f3"

[versions]
minecraft = "1.18.2"
quilt = "0.16.0"
