name = "SomeMechanics"
author = "MisileLaboratory"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "505ad3bb6fadafa4258c2206d98c92a68997a86845534b376444bfd5a44945f4"

[versions]
forge = "40.1.19"
minecraft = "1.18.2"
